### ISSUE TITLE
Building on OSX Catalina

### ISSUE THREAD

**Issue by silentbugs** [Aorimn/dislocker#223]
Trying to build under latest OSX Catalina and getting the following errors, regarding "PolarSSL", whose version cannot be found. After a bit of research it seems like PolarSSL has been replaced with mbedTLS, which is installed on my system via homebrew (mbedtls).

The reason I'm trying to build is because the version on homebrew (0.7.1) gives segmentation faults on my encrypted external hard drive and I believe the commits resolve the issue (the drive has been encrypted with windows 10 pro 1903 bitlocker).

Currently trying to build with:

mbedtls==2.23.0
ruby==2.6

The errors:

```
~/path/to/dislocker (git)-[master] % cmake .
a.c:2:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
PolarSSL/mbedTLS version:
CMake Error at cmake/FindPolarSSL.cmake:83 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:115 (find_package)


CMake Error at cmake/FindPolarSSL.cmake:85 (list):
  list sub-command GET requires at least three arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:115 (find_package)


CMake Error at cmake/FindPolarSSL.cmake:86 (list):
  list sub-command GET requires at least three arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:115 (find_package)


CMake Error at cmake/FindPolarSSL.cmake:87 (list):
  list sub-command GET requires at least three arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:115 (find_package)


-- --------FindRuby.cmake debug------------
-- _RUBY_POSSIBLE_EXECUTABLE_NAMES: ruby;ruby2.5;ruby25;ruby2.4;ruby24;ruby2.3;ruby23;ruby2.2;ruby22;ruby2.1;ruby21;ruby2.0;ruby20;ruby1.9;ruby19;ruby1.8;ruby18
-- _RUBY_POSSIBLE_LIB_NAMES: ruby;ruby-static;ruby2.6;ruby26;ruby-2.6;ruby-2.6.3
-- RUBY_ARCH_DIR: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
-- RUBY_HDR_DIR: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0
-- RUBY_POSSIBLE_LIB_DIR: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
-- Found RUBY_VERSION: "2.6.3" , short: "2.6", nodot: "26"
-- _RUBY_REQUIRED_VARS: RUBY_EXECUTABLE;RUBY_INCLUDE_DIR;RUBY_LIBRARY;RUBY_CONFIG_INCLUDE_DIR
-- RUBY_EXECUTABLE: /usr/bin/ruby
-- RUBY_LIBRARY: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/ruby.framework
-- RUBY_INCLUDE_DIR: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Headers
-- RUBY_CONFIG_INCLUDE_DIR: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Headers
-- --------------------
-- Configuring incomplete, errors occurred!
See also "/path/to/dislocker/CMakeFiles/CMakeOutput.log".
```

**Comment by silentbugs** [comment]
Even hacking my way around MBEDTLS version, there's still more issues with building which I don't know if they should be opened as separate issues. Summary:

* library osxfuse_i64 isn't found with latest osxfuse installed
* Windows 10 1903 exFAT fix does not compile (issue with BLKGETSIZE64)
* BLKSSZGET does not exist

I'm generally wondering if I should try and hack around things to see if the library will work, or if trying to get it to compile in Catalina is a lost cause.

**Comment by silentbugs** [comment]
In case anyone else comes here, I've managed to build this successfully in Catalina and will update things soon (possibly either PR or comments here). @Aorimn is it possible to upload my build to homebrew for other OSX users? The current version in homebrew is not really useable.

**Comment by Franz-65** [comment]
Yes that would be great, I would be very happy about it. It doesn't work with MacOS Catalina at the moment :-(

**Comment by Aorimn** [comment]
The build should be fixed by the 0.7.2 (see https://travis-ci.org/github/Aorimn/dislocker/jobs/744239349), but this isn't Catalina (the issue I fixed wasn't specific to Catalina but I don't know if there are others lurking about).

Feel free to reopen the bug again (with the compilation details) if it fails.

**Comment by silentbugs** [comment]
Some final thoughts:

Everything seems to be patched, but building on Catalina might still fail for some people. For me it was due to '<stdio.h>' not being located because /usr/include has moved in Catalina, and therefore my Catalina 'cc' command (which is actaully '/Library/Developer/CommandLineTools/usr/bin/cc') cannot find the header file. Maybe I have something misconfigured, it seems like there should have been a /Library/Developer/CommandLineTools/usr/include directory as well.

Either way, to fix this I just used the SDK's include directory as my CPATH directory and building works fine:

`CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include cmake .`

**Comment by Tom9876** [comment]
Thanks to the hints of @silentbugs I got it build (although it is not anymor necessary as brew now also installs the recent version). The missing part was the LIBRARY_PATH. I use the following command (as one line):
`LIBRARY_PATH=/usr/local/lib:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include cmake .`
